// <auto-generated />
namespace GeeksForLessForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adduserIdtotables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduserIdtotables));
        
        string IMigrationMetadata.Id
        {
            get { return "201903031730549_add userId to tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
